# Generated by Django 3.2 on 2022-04-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20220410_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitems',
            name='category',
            field=models.CharField(choices=[('Starters', 'Starters'), ('Main Courses', 'Main Courses'), ('Side Orders', 'Side Orders'), ('Desserts', 'Desserts')], default='Main Courses', max_length=30),
        ),
    ]
