# Generated by Django 3.2 on 2022-04-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menuitems_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitems',
            name='price',
            field=models.CharField(default='$10.00', max_length=20),
        ),
    ]
