# Generated by Django 3.2 on 2022-04-03 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='leavning_time',
            new_name='leaving_time',
        ),
    ]
