# Generated by Django 3.2 on 2022-04-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_rename_leavning_time_book_leaving_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.IntegerField(choices=[('Pending', 'Pending'), ('Confirmed', 'Booked')], default='Pending'),
        ),
    ]
