# Generated by Django 3.2 on 2022-04-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_alter_book_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='arrival_time',
            field=models.DateTimeField(default='%Y-%m-%d %H:%M'),
        ),
    ]
