# Generated by Django 3.2 on 2022-04-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_alter_book_arrival_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='arrival_time',
            field=models.DateTimeField(),
        ),
    ]
