# Generated by Django 3.2 on 2022-04-06 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservation', '0006_alter_book_arrival_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('num_of_guests', models.PositiveIntegerField(default=2)),
                ('arrival_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('leaving_time', models.TimeField()),
                ('special_requests', models.TextField(blank=True, max_length=300)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Booked')], default=0)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
