# Generated by Django 3.2 on 2022-04-07 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_alter_booking_arrival_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='arrival_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
