# Generated by Django 3.2 on 2022-04-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0011_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Booked')], default=0),
        ),
    ]
