# Generated by Django 3.2 on 2022-04-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0012_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='leaving_time',
            field=models.TimeField(blank=True),
        ),
    ]
